language: php

php:
- 7.1
- 7.2
- nightly

matrix:
  allow_failures:
  - php: nightly

env:
- COMPOSER_OPTS=""
- COMPOSER_OPTS="--prefer-lowest"

before_script:
- travis_retry composer self-update
- travis_retry composer update $COMPOSER_OPTS

script:
- vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
- wget https://scrutinizer-ci.com/ocular.phar
- php ocular.phar code-coverage:upload --format=php-clover coverage.clover

dist: trusty
sudo: false
